/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import Core.Producto;
import Core.Rol;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.apache.commons.lang3.math.NumberUtils;
import repositorio.Dao;

/**
 *
 * @author losmelli
 */
public class AdministrarProducto extends javax.swing.JFrame {

    private Dao<Producto> dao;
    private Rol rol;

    /**
     * Creates new form InsertarProducto
     */
    public AdministrarProducto(Dao<Producto> dao, Rol rol) {
        initComponents();
        this.dao = dao;
        this.rol = rol;
        AdministrarVista();

    }

    private void AdministrarVista() {
        if (this.rol.equals(Rol.Cajero)) {

            NombreField.setEditable(false);
            MarcaField.setEditable(false);
            PrecioField.setEditable(false);
            InsertarButton.setEnabled(false);
            EliminarProductoButton.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        InsertarButton = new javax.swing.JButton();
        NombreField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        MarcaField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CantidadField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        CodigoField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        EliminarProductoButton = new javax.swing.JButton();
        ModificarProducto = new javax.swing.JButton();
        BuscarButton = new javax.swing.JButton();
        PrecioField = new javax.swing.JTextField();

        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel5.setText("Marca de Producto");

        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel7.setText("Precio");

        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel8.setText("Precio");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        InsertarButton.setText("Insertar");
        InsertarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertarButtonActionPerformed(evt);
            }
        });

        NombreField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel1.setText("Nombre ");

        jLabel2.setText("Cantidad");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Administrar Productos");

        MarcaField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel4.setText("Marca ");

        CantidadField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel6.setText("Precio");

        CodigoField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel9.setText("Codigo de Barra");

        EliminarProductoButton.setText("Eliminar");
        EliminarProductoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarProductoButtonActionPerformed(evt);
            }
        });

        ModificarProducto.setText("Modificar");
        ModificarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarProductoActionPerformed(evt);
            }
        });

        BuscarButton.setText("Buscar Producto");
        BuscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarButtonActionPerformed(evt);
            }
        });

        PrecioField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(InsertarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(ModificarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EliminarProductoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel6))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(PrecioField)
                            .addComponent(CodigoField)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                            .addComponent(NombreField)
                            .addComponent(MarcaField)
                            .addComponent(CantidadField))
                        .addGap(18, 18, 18)
                        .addComponent(BuscarButton)
                        .addContainerGap(15, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(BuscarButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CodigoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MarcaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(PrecioField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CantidadField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InsertarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ModificarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EliminarProductoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InsertarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertarButtonActionPerformed
        if (verificarCamposVacios()) {
            JOptionPane.showMessageDialog(null, "Campos Vacios");
            return;
        }
        Producto producto = obtenerProductoUI();
        if(producto == null) return;
        try {
            Producto productoDb = dao.get(producto.getId());
            if (productoDb == null) {
                dao.add(producto);
                JOptionPane.showMessageDialog(null, "Producto Insertado Correctamente");
            } else if (productoDb.getActivo() == 0) {
                dao.update(producto);
                JOptionPane.showMessageDialog(null, "Producto Insertado Correctamente");
            } else if (productoDb.getActivo() == 1) {
                JOptionPane.showMessageDialog(null, "Producto ya existente");
            }
            limpiarCampos();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Ocurrio un error");
            Logger.getLogger(AdministrarProducto.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_InsertarButtonActionPerformed

    private void EliminarProductoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarProductoButtonActionPerformed
        if (verificarCamposVacios()) {
            JOptionPane.showMessageDialog(null, "Campos Vacios");
            return;
        }

        Producto producto = obtenerProductoUI();
        if (producto == null) {
            return;
        }
        try {
            Producto productoDb = dao.get(producto.getId());
            if (productoDb == null || productoDb.getActivo() == 0) {
                JOptionPane.showMessageDialog(null, "Producto No Existente");
                return;
            } else if (productoDb.getActivo() == 1) {
                dao.delete(producto.getId());
            }

            limpiarCampos();
            JOptionPane.showMessageDialog(null, "Producto Eliminado Correctamente");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Ocurrio un error");
            Logger.getLogger(AdministrarProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_EliminarProductoButtonActionPerformed

    private void ModificarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarProductoActionPerformed
        if (rol.equals(Rol.Cajero)) {
            CodigoField.setEnabled(true);
        }
        if (verificarCamposVacios()) {
            JOptionPane.showMessageDialog(null, "Campos Vacios");
            return;
        }
        Producto producto = obtenerProductoUI();
        if (producto == null) {
            return;
        }
        try {
            Producto productoDb = dao.get(producto.getId());
            if (productoDb == null || productoDb.getActivo() == 0) {
                JOptionPane.showMessageDialog(null, "Producto No Existente");
                return;
            } else if (productoDb.getActivo() == 1) {
                dao.update(producto);
            }
            JOptionPane.showMessageDialog(null, "Producto Actualizado Correctamente");
            limpiarCampos();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Ocurrio un error");
            Logger.getLogger(AdministrarProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ModificarProductoActionPerformed

    private void BuscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarButtonActionPerformed
        try {

            if (CodigoField.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "ingrese un valor valido");
                return;
            }

            if (!NumberUtils.isParsable(CodigoField.getText())) {
                JOptionPane.showMessageDialog(null, "ingrese un valor valido");
                return;
            }

            Producto producto = dao.get(CodigoField.getText());
            if (producto == null || producto.getActivo() == 0) {
                JOptionPane.showMessageDialog(null, "Producto no Encontrado");
                limpiarCampos();
            } else {
                if (rol.equals(Rol.Cajero)) {
                    CodigoField.setEnabled(false);
                }
                NombreField.setText(producto.getNombre());
                MarcaField.setText(producto.getMarca());
                PrecioField.setText(String.valueOf(producto.getPrecio()));
                CantidadField.setText(String.valueOf(producto.getCantidad()));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Ocurrio un error");
            Logger.getLogger(AdministrarProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BuscarButtonActionPerformed

    private void limpiarCampos() {
        CodigoField.setText("");
        NombreField.setText("");
        MarcaField.setText("");
        PrecioField.setText("");
        CantidadField.setText("");
    }

    private Producto obtenerProductoUI() {
        int codigoBarra = Integer.parseInt(CodigoField.getText());
        String nombre = NombreField.getText();
        String marca = MarcaField.getText();
        String precioStr = PrecioField.getText();
        if (!NumberUtils.isParsable(precioStr)) {
            JOptionPane.showMessageDialog(null, "Ingrese valores validos");
            return null;
        }
        float precio = Float.parseFloat(PrecioField.getText());      
        if (!NumberUtils.isParsable(precioStr)) {
            JOptionPane.showMessageDialog(null, "Ingrese valores validos");
            return null;
        }
        String cantStr = CantidadField.getText();
        if (!NumberUtils.isParsable(cantStr)) {
            JOptionPane.showMessageDialog(null, "Ingrese valores validos");
            return null;
        }
        float cantFloat = Float.parseFloat(cantStr);
        int cantidad = Integer.parseInt(CantidadField.getText());
        if (cantFloat - cantidad != 0) {
            JOptionPane.showMessageDialog(null, "Ingrese valores validos");
            return null;
        }
        return new Producto(codigoBarra, nombre, precio, marca, cantidad, 1);
    }

    private boolean verificarCamposVacios() {
        return CodigoField.getText().equals("")
                || NombreField.getText().equals("")
                || MarcaField.getText().equals("")
                || PrecioField.getText().equals("")
                || CantidadField.getText().equals("");
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarButton;
    private javax.swing.JTextField CantidadField;
    private javax.swing.JTextField CodigoField;
    private javax.swing.JButton EliminarProductoButton;
    private javax.swing.JButton InsertarButton;
    private javax.swing.JTextField MarcaField;
    private javax.swing.JButton ModificarProducto;
    private javax.swing.JTextField NombreField;
    private javax.swing.JTextField PrecioField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
