/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import Core.Caja;
import Core.Kiosco;
import Core.Rol;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.apache.commons.lang3.math.NumberUtils;
import repositorio.ProductoDao;

/**
 *
 * @author losmelli
 */
public class VistaCajero extends javax.swing.JFrame {

    /**
     * Creates new form VistaUsuario
     */
    public VistaCajero() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AdministrarStockButton = new javax.swing.JButton();
        RealizarVentaButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        AbrirCajaButton = new javax.swing.JButton();
        CerrarCajaButton = new javax.swing.JButton();
        CerrarSesionButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        AdministrarStockButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        AdministrarStockButton.setText("Administrar Stock");
        AdministrarStockButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdministrarStockButtonActionPerformed(evt);
            }
        });

        RealizarVentaButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        RealizarVentaButton.setText("Realizar Venta");
        RealizarVentaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RealizarVentaButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Usuario");

        AbrirCajaButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        AbrirCajaButton.setText("Abrir Caja");
        AbrirCajaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirCajaButtonActionPerformed(evt);
            }
        });

        CerrarCajaButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        CerrarCajaButton.setText("Cerrar Caja");
        CerrarCajaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarCajaButtonActionPerformed(evt);
            }
        });

        CerrarSesionButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CerrarSesionButton.setText("Cerrar Sesion");
        CerrarSesionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarSesionButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RealizarVentaButton, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                    .addComponent(AbrirCajaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AdministrarStockButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CerrarCajaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(229, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CerrarSesionButton)
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CerrarSesionButton))
                .addGap(80, 80, 80)
                .addComponent(RealizarVentaButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AdministrarStockButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AbrirCajaButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CerrarCajaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AdministrarStockButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdministrarStockButtonActionPerformed
        JFrame ventana = new AdministrarProducto(new ProductoDao(),Rol.Cajero);
        ventana.setVisible(true);
    }//GEN-LAST:event_AdministrarStockButtonActionPerformed

    private void RealizarVentaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RealizarVentaButtonActionPerformed
       if(Caja.getInstance().estaCerrada()){
           JOptionPane.showMessageDialog(null,"Tiene que Abrir la Caja para continuar");
           return;
       }
       JFrame ventana = new RegistrarVenta();
       ventana.setVisible(true);
    }//GEN-LAST:event_RealizarVentaButtonActionPerformed

    private void AbrirCajaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirCajaButtonActionPerformed
        if(!Caja.getInstance().estaCerrada()){
           JOptionPane.showMessageDialog(null,"La Caja ya esta Abierta");
           return;
       }        
       String valor = JOptionPane.showInputDialog(null,"Ingrese El Valor de Apertura de la Caja");
       if(!NumberUtils.isParsable(valor)){
           JOptionPane.showMessageDialog(null, "Ingrese un valor Valido");
           return;
       }
       Kiosco.abrirCaja(Float.parseFloat(valor));
    }//GEN-LAST:event_AbrirCajaButtonActionPerformed

    private void CerrarCajaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarCajaButtonActionPerformed
        if(Caja.getInstance().estaCerrada()){
           JOptionPane.showMessageDialog(null,"La Caja ya esta Cerrada");
           return;
       }
       
       Kiosco.cerrarCaja();
    }//GEN-LAST:event_CerrarCajaButtonActionPerformed

    private void CerrarSesionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarSesionButtonActionPerformed
        JFrame ventana = new Login();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CerrarSesionButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaCajero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AbrirCajaButton;
    private javax.swing.JButton AdministrarStockButton;
    private javax.swing.JButton CerrarCajaButton;
    private javax.swing.JButton CerrarSesionButton;
    private javax.swing.JButton RealizarVentaButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
